// Code generated by swaggo/swag. DO NOT EDIT
package doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/logs": {
            "get": {
                "description": "Provider can list all available log files using signature authentication",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "List available log files",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider's address",
                        "name": "Address",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JSON session token with address, provider, timestamp, expiresAt, nonce",
                        "name": "Session-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature of the session token",
                        "name": "Session-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Component name (broker/event), default: both",
                        "name": "component",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of log files",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/logs/{component}/{filename}": {
            "get": {
                "description": "Provider can download a specific log file using signature authentication",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Download a specific log file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Provider's address",
                        "name": "Address",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JSON session token with address, provider, timestamp, expiresAt, nonce",
                        "name": "Session-Token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Signature of the session token",
                        "name": "Session-Signature",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Component name (broker/event)",
                        "name": "component",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Log file name",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Log file content",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid component or filename",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Log file not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/quote": {
            "get": {
                "description": "This endpoint allows you to get a quote",
                "tags": [
                    "quote"
                ],
                "operationId": "getQuote",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/quote/verify/gpu": {
            "post": {
                "description": "This endpoint proxies attestation report verification requests to NVIDIA's TEE verification service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "proxy"
                ],
                "operationId": "VerifyGPU",
                "parameters": [
                    {
                        "description": "Raw request body to forward",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/request": {
            "get": {
                "description": "This endpoint allows you to list requests",
                "tags": [
                    "request"
                ],
                "operationId": "listRequest",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Processed",
                        "name": "processed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RequestList"
                        }
                    }
                }
            }
        },
        "/service": {
            "get": {
                "description": "This endpoint allows you to list all services in the contract",
                "tags": [
                    "service"
                ],
                "operationId": "getService",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ServiceList"
                        }
                    }
                }
            }
        },
        "/settle": {
            "post": {
                "description": "This endpoint allows you to settle fees for requests from users",
                "tags": [
                    "settle"
                ],
                "operationId": "settleFees",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/sync-account": {
            "post": {
                "description": "This endpoint allows you to synchronize information of all accounts from the contract",
                "tags": [
                    "user"
                ],
                "operationId": "syncUserAccounts",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/user/{user}/sync": {
            "post": {
                "description": "This endpoint allows you to synchronize information of single account from the contract",
                "tags": [
                    "user"
                ],
                "operationId": "syncUserAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User address",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ListMeta": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Request": {
            "type": "object",
            "required": [
                "fee",
                "inputFee",
                "nonce",
                "outputFee",
                "requestHash",
                "serviceName",
                "signature",
                "teeSignature",
                "userAddress"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "readOnly": true
                },
                "fee": {
                    "type": "string"
                },
                "inputCount": {
                    "description": "Optimized count fields for efficient aggregation",
                    "type": "integer"
                },
                "inputFee": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "outputCount": {
                    "type": "integer"
                },
                "outputFee": {
                    "type": "string"
                },
                "processed": {
                    "type": "boolean"
                },
                "requestHash": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "skipUntil": {
                    "description": "Skip this request in settlement until this time",
                    "type": "string"
                },
                "teeSignature": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "readOnly": true
                },
                "userAddress": {
                    "type": "string"
                },
                "vllmProxy": {
                    "type": "boolean"
                }
            }
        },
        "model.RequestList": {
            "type": "object",
            "properties": {
                "fee": {
                    "description": "Use string to handle large values exceeding int64 max",
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Request"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/model.ListMeta"
                }
            }
        },
        "model.Service": {
            "type": "object",
            "required": [
                "inputPrice",
                "model",
                "name",
                "outputPrice",
                "teeSignerAcknowledged",
                "type",
                "url",
                "verifiability"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "readOnly": true
                },
                "inputPrice": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "outputPrice": {
                    "type": "string"
                },
                "teeSignerAcknowledged": {
                    "type": "boolean"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "readOnly": true
                },
                "url": {
                    "type": "string"
                },
                "verifiability": {
                    "type": "string"
                }
            }
        },
        "model.ServiceList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Service"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/model.ListMeta"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:3080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "0G Serving Provider Broker API",
	Description:      "These APIs allow providers to manage services and user accounts. The host is localhost, and the port is configured in the provider's configuration file, defaulting to 3080.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
