address:
contractAddress: 0x576E5761405Eee607089E34feFE7Da2E33c6851e
database:
  provider: root:123456@tcp(localhost:3306)/provider?parseTime=true
  user: root:123456@tcp(localhost:3306)/user?parseTime=true
privateKey:
chainUrl: https://rpc-testnet.0g.ai
servingUrl: http://localhost:8080
customGasLimit: 10000000
customGasPrice: 10000000
