address:
contractAddress: 0x0e6EA4ceb807e778bCC0Ee62AB5a6360f763646C
mysql: root:123456@tcp(localhost:3306)/serving?parseTime=true
privateKey:
chainUrl: https://rpc-testnet.0g.ai
servingUrl: http://localhost:8080
customGasLimit: 100000
customGasPrice: 100000
