address:
contractAddress: 0xaC622c6A20bE02C8794c346439b8Ca01703D69B7
mysql: root:123456@tcp(localhost:3306)/serving?parseTime=true
privateKey:
chainUrl: https://rpc-testnet.0g.ai
servingUrl: http://localhost:8081
customGasLimit: 100000
customGasPrice: 100000
