address: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
interval:
  autoSettleBufferTime: 18000
  forceSettlementProcessor: 86400
  settlementProcessor: 600
servingUrl: http://localhost:8080
networks:
  ethereum0g:
    url: "https://rpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
