package config

import (
	"fmt"
	"io"
	"reflect"
	"sort"
	"strings"
	"time"
)

// FieldDoc captures everything --print-config-help needs to render one
// row in the operator-facing reference. Built once at startup (or on
// demand) by walkDocs.
type FieldDoc struct {
	Path        string  // dotted yaml path, e.g. "service.inputPrice"
	EnvName     string  // BROKER_*-prefixed env name, "" for runtime-only fields
	GoType      string  // "string" / "time.Duration" / "[]string" / "JSON([]PricingTier)" / etc.
	Kind        envKind // matches the env decoding path
	Default     string  // raw default tag value, "" if no default
	Description string  // desc tag value
	Secret      bool    // secret:"true" tag presence
	Deprecated  bool    // included for completeness; the env walker already skips these
}

// WalkConfigFields builds a sorted-by-path slice of FieldDoc records for the
// inference Config schema. Skips deprecated fields (they're never user-facing
// post-#507) and yaml:"-" runtime fields, except for the LoRA ECIES secret
// which is documented as a special case because it ships via env.
func WalkConfigFields() []FieldDoc {
	out := []FieldDoc{}
	walkDocs(reflect.TypeOf(Config{}), "", &out)
	// Special case: LoRA.EciesPrivateKey is yaml:"-" but env-configurable.
	out = append(out, FieldDoc{
		Path:        "lora.eciesPrivateKey",
		EnvName:     "BROKER_LORA_ECIES_PRIVATE_KEY",
		GoType:      "string",
		Kind:        envScalar,
		Description: "ECIES private key for adapter decryption (2-CVM setup). Set via env only.",
		Secret:      true,
	})
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

func walkDocs(t reflect.Type, path string, out *[]FieldDoc) {
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct {
		return
	}
	for i := 0; i < t.NumField(); i++ {
		ft := t.Field(i)
		if !ft.IsExported() {
			continue
		}
		yamlTag := ft.Tag.Get("yaml")
		yamlName := strings.SplitN(yamlTag, ",", 2)[0]
		if yamlName == "-" || yamlName == "" {
			continue
		}
		_, deprecated := ft.Tag.Lookup("deprecated")
		if deprecated {
			continue
		}
		fieldPath := joinPath(path, yamlName)
		kind, recurse := classifyEnvField(ft.Type)
		if recurse {
			t2 := ft.Type
			if t2.Kind() == reflect.Ptr {
				t2 = t2.Elem()
			}
			walkDocs(t2, fieldPath, out)
			continue
		}
		desc, _ := ft.Tag.Lookup("desc")
		def, _ := ft.Tag.Lookup("default")
		_, secret := ft.Tag.Lookup("secret")
		*out = append(*out, FieldDoc{
			Path:        fieldPath,
			EnvName:     envPrefix + toEnvName(fieldPath),
			GoType:      formatGoType(ft.Type),
			Kind:        kind,
			Default:     def,
			Description: desc,
			Secret:      secret,
		})
	}
}

func formatGoType(t reflect.Type) string {
	if t == reflect.TypeOf(time.Duration(0)) {
		return "time.Duration"
	}
	switch t.Kind() {
	case reflect.Slice:
		return "[]" + formatGoType(t.Elem())
	case reflect.Map:
		return fmt.Sprintf("map[%s]%s", t.Key().Kind(), formatGoType(t.Elem()))
	case reflect.Ptr:
		return "*" + formatGoType(t.Elem())
	case reflect.Struct:
		if t.Name() != "" {
			return t.Name()
		}
		return "struct"
	default:
		return t.Kind().String()
	}
}

// RenderTextHelp writes a fixed-width 3-column table to w: path | env | default.
// Designed for terminal output via `--print-config-help`.
func RenderTextHelp(w io.Writer) error {
	docs := WalkConfigFields()
	const pad = 2
	wPath, wEnv := len("PATH"), len("ENV")
	for _, d := range docs {
		if l := len(d.Path); l > wPath {
			wPath = l
		}
		if l := len(d.EnvName); l > wEnv {
			wEnv = l
		}
	}
	fmt.Fprintf(w, "%-*s  %-*s  DEFAULT\n", wPath, "PATH", wEnv, "ENV")
	fmt.Fprintf(w, "%s  %s  %s\n", strings.Repeat("-", wPath), strings.Repeat("-", wEnv), strings.Repeat("-", 16))
	_ = pad
	for _, d := range docs {
		marker := ""
		if d.Secret {
			marker = " 🔒"
		}
		fmt.Fprintf(w, "%-*s  %-*s  %s%s\n", wPath, d.Path, wEnv, d.EnvName, defaultDisplay(d.Default), marker)
	}
	return nil
}

// RenderMarkdown writes docs/CONFIG.md-flavored markdown to w. Stable output
// (sorted by path, no timestamps, no random ordering) so the CI can run
// `make docs && git diff --exit-code`.
func RenderMarkdown(w io.Writer) error {
	docs := WalkConfigFields()
	fmt.Fprintln(w, "# Inference Broker Configuration Reference")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Generated by `0g-inference-server --print-config-help --markdown`. Do not edit by hand — update struct tags in `api/inference/config/config.go` and re-run `make docs`.")
	fmt.Fprintln(w)
	fmt.Fprintln(w, "Layering order: `default:` struct tags → yaml file (`CONFIG_FILE`, default `/etc/config/config.yaml`) → `BROKER_*` env vars. Env wins; yaml wins over defaults.")
	fmt.Fprintln(w)
	for _, d := range docs {
		title := "`" + d.Path + "`"
		if d.Secret {
			title += " 🔒"
		}
		fmt.Fprintf(w, "### %s\n", title)
		fmt.Fprintf(w, "- **Env**: `%s`%s\n", d.EnvName, envFormatNote(d.Kind))
		fmt.Fprintf(w, "- **Type**: `%s`\n", d.GoType)
		fmt.Fprintf(w, "- **Default**: %s\n", defaultMarkdown(d.Default))
		if d.Description != "" {
			fmt.Fprintf(w, "- **Description**: %s\n", d.Description)
		}
		fmt.Fprintln(w)
	}
	return nil
}

func envFormatNote(k envKind) string {
	switch k {
	case envDuration:
		return " (duration string, e.g. `1h`, `30s`)"
	case envStringSlice:
		return " (comma-separated)"
	case envJSON:
		return " (JSON-encoded)"
	default:
		return ""
	}
}

func defaultDisplay(def string) string {
	if def == "" {
		return "—"
	}
	return def
}

func defaultMarkdown(def string) string {
	if def == "" {
		return "_(none)_"
	}
	return "`" + def + "`"
}

// RenderEffectiveConfig writes cfg as yaml to w. Fields marked secret:"true"
// (and the legacy LORA ECIES private key) are replaced with "***" so the
// output is safe to paste into a bug report.
//
// The current implementation pretty-prints via yaml.v3 since that's what's
// already in the dep graph; if the diff between yaml.v3 and yaml.v2 ever
// shows up here (e.g. anchor handling), this is the place to swap.
func RenderEffectiveConfig(cfg *Config, w io.Writer) error {
	// Defer the yaml marshal to its own file (effective.go) so this file
	// can stay close-to-stdlib and easy to read.
	return renderEffectiveYAML(cfg, w)
}
