basePath: /v1
definitions:
  schema.Task:
    properties:
      createdAt:
        readOnly: true
        type: string
      customerAddress:
        type: string
      datasetkHash:
        type: string
      deliverIndex:
        type: integer
      encryptedSecret:
        type: string
      fee:
        type: string
      id:
        readOnly: true
        type: string
      nonce:
        type: string
      outputRootHash:
        readOnly: true
        type: string
      preTrainedModelHash:
        type: string
      serviceName:
        type: string
      signature:
        type: string
      status:
        type: string
      teeSignature:
        type: string
      trainingParams:
        type: string
      updatedAt:
        readOnly: true
        type: string
    required:
    - customerAddress
    - datasetkHash
    - preTrainedModelHash
    - trainingParams
    type: object
host: localhost:3080
info:
  contact: {}
  description: These APIs allows customers to interact with the 0G Compute Fine Tune
    Service
  title: 0G Serving Provider Broker API
  version: 0.2.0
paths:
  /quote:
    get:
      description: This endpoint allows you to get quote
      operationId: getQuote
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - quote
  /task:
    post:
      description: This endpoint allows you to create fine tune task
      operationId: createTask
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/schema.Task'
      responses:
        "204":
          description: No Content - success without response body
      tags:
      - task
  /task/{id}:
    get:
      description: This endpoint allows you to get task by name
      operationId: getTask
      parameters:
      - description: task ID
        in: path
        name: taskID
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schema.Task'
      tags:
      - task
  /tasks/{taskID}/progress:
    get:
      parameters:
      - description: Task ID
        in: path
        name: taskID
        required: true
        type: string
      produces:
      - application/octet-stream
      responses:
        "200":
          description: progress.log
          schema:
            type: file
      tags:
      - tasks
swagger: "2.0"
