interval:
  autoSettleBufferTime: 60
  forceSettlementProcessor: 600
  settlementProcessor: 300
database:
  provider: root:123456@tcp(0g-serving-broker-db:3306)/provider?parseTime=true
servingUrl: http://0g-serving-provider-broker:3080
networks:
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16601
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
zkProver:
  provider: "zk-server:3000"
  requestLength: 40
monitor:
  enable: true
  eventAddress: "0g-serving-provider-event:3081"
