// Package audiospec answers one question, per audio-generation vendor: for an
// OpenAI-shaped create request, what is the MOST output audio that vendor can
// bill for.
//
// It is videospec's sibling and exists for the same reason — the translator and
// the broker must not derive that answer separately, because a create is billed
// asynchronously, minutes later, and a gate that reads a request differently from
// the code that builds the vendor call has already let the audio be generated by
// the time the real bill arrives. Two independent readings of one request cannot
// be kept in agreement, so both sides call this.
//
// # Why this is a BOUND where videospec is an estimate
//
// The difference is not stylistic and is worth stating before the interface.
//
// videospec's central question is "what WILL this vendor render" — a video
// vendor's duration is chosen from the request, its resolution tier is derived,
// and for a token-billed vendor the billable quantity is a formula over both. So
// videospec.TokenEstimator's doc is explicit that it returns an ESTIMATE the
// balance gate tolerates drift on, and ctrl.WarnVideoTokenEstimateDrift exists to
// watch it going wrong.
//
// An audio vendor publishes a hard per-request output ceiling (Seed Audio: 120
// seconds). So the question here is "what is the MOST this can cost", and the
// answer is a genuine upper bound: the bill cannot exceed the hold. That makes
// the contract smaller — one method, one number, no outcome enum — and it means
// nothing here needs a drift warning. It also means concurrent creates from one
// wallet see each other exactly rather than approximately, which is the property
// the minimum-locked-balance floor exists to paper over when it does not hold.
//
// Do not "improve" ReserveSeconds into a prediction of the actual length. A
// prediction that comes in low is indistinguishable from a correct bound until
// the bill arrives, and it arrives after the audio exists.
//
// # What is shared and what is not
//
// As in videospec, this file holds only the contract and the genuinely
// vendor-independent parts. Each vendor implements Spec in its own file and keeps
// its own rules; adding a vendor means adding ITS file and touching nothing else.
// There is deliberately no struct describing "the shape of a vendor's rules" —
// one sample is not a general form, and videospec's own doc records what happened
// when two samples looked alike and a third did not.
package audiospec

import (
	"math"
	"strconv"
	"strings"
)

// Vendor identifies an audio-generation vendor. A deployment names one; it is a
// statement about which upstream is behind the translator, not a tunable.
type Vendor string

// Spec is what a vendor must be able to answer. Implementations live one per
// vendor file and share no structure — see the package doc.
type Spec interface {
	// MaxOutputSeconds is this vendor's hard per-request output ceiling, in
	// seconds. It is a fact about the vendor, not an operator's choice: a
	// deployment cannot raise it, and a request asking for more does not get
	// more.
	MaxOutputSeconds() int64

	// ReserveSeconds reports the greatest number of output seconds this vendor
	// can bill for a create request whose raw `max_duration` field is rawMax.
	//
	// It ALWAYS returns a usable bound in (0, MaxOutputSeconds]. There is no
	// "cannot tell" outcome, and that is the point: an absent, unreadable,
	// negative or absurd max_duration all mean the same thing here — the vendor
	// will decide the length itself, subject to its own ceiling — so the ceiling
	// is the honest answer in every one of those cases.
	//
	// This is where audio diverges from videospec.SecondsOutcome, which must
	// distinguish "resolved" from "vendor decides" from "refuse" because a video
	// vendor with no ceiling has no safe number to fall back on. Collapsing those
	// three into one number is only correct BECAUSE a ceiling exists; a vendor
	// without one does not belong behind this interface.
	ReserveSeconds(rawMax string) int64
}

// specs is the registry, filled by each vendor's own file at init. Nothing
// enumerates vendors here.
//
// A vendor absent from it has no rules recorded, which callers must treat as
// "unknown", never as "assume the common case" — a guessed ceiling is a guessed
// hold.
var specs = map[Vendor]Spec{}

// register records one vendor's rules. Called from that vendor's own file at
// package init.
//
// It panics on a duplicate or an empty name rather than letting the last
// registration win: two files claiming one vendor is a merge accident, and which
// one wins would then depend on file order — with the losing set of rules
// silently sizing every reservation for that vendor.
func register(v Vendor, s Spec) {
	if v == "" {
		panic("audiospec: registered a spec with no vendor name")
	}
	if _, dup := specs[v]; dup {
		panic("audiospec: duplicate rules registered for vendor " + string(v))
	}
	specs[v] = s
}

// Get returns the rules recorded for a vendor. ok is false for a vendor nobody
// has recorded rules for — a caller that needs to hold funds must degrade
// explicitly there (forward unreserved and count it), not guess a ceiling.
func Get(v Vendor) (Spec, bool) {
	s, ok := specs[Vendor(strings.ToLower(strings.TrimSpace(string(v))))]
	return s, ok
}

// maxRepresentableSeconds bounds a duration this package will read at all.
//
// Vendor-independent, which is why it lives here: it is not a vendor's rule but
// ours, guarding the float-to-int64 conversion every implementation performs.
// Past it the conversion is implementation-defined (MinInt64 on amd64), which a
// vendor's clamp would then move UP to its ceiling — the right answer by
// accident, via a path nothing tests. Rejecting here makes the ceiling the
// answer on purpose.
const maxRepresentableSeconds = 1 << 40

// ParseMaxDuration reads a raw `max_duration` field into a positive,
// representable float for a vendor implementation to apply its own ceiling to.
//
// ok=false means "no usable number in this field", which every implementation
// answers the same way — with its ceiling. Unlike videospec.ParseSeconds there is
// no separate `rejected` outcome, because there is nothing for a caller to do
// differently: an out-of-range value and an unreadable one both leave the vendor
// choosing the length, and both are bounded by the same ceiling.
//
// raw IS trimmed, unlike videospec's counterpart. That rule exists there to match
// vendor-side readers that receive the client's raw string; here the translator
// parses the field itself and sends the vendor a normalized integer, so the reader
// this must agree with is the translator's — and trimming is what keeps the two in
// agreement. Same reasoning as seedance.NormalizeSeconds, which deviates from the
// same rule for the same reason.
func ParseMaxDuration(raw string) (value float64, ok bool) {
	f, err := strconv.ParseFloat(strings.TrimSpace(raw), 64)
	if err != nil || math.IsNaN(f) || math.IsInf(f, 0) || f > maxRepresentableSeconds || !(f > 0) {
		return 0, false
	}
	return f, true
}
