// Package audiospec answers one question, per audio-generation vendor: what is
// the MOST output audio one request to that vendor can bill for.
//
// It is videospec's sibling and exists for the same reason — the balance gate and
// the billing path must not derive that answer separately. The gate holds funds
// before the vendor is called; the bill arrives after the audio exists. A gate
// that reads the bound differently from the code that bills has already let the
// audio be generated by the time the disagreement shows up. So both sides call
// this.
//
// # Why this is a BOUND where videospec is an estimate
//
// The difference is not stylistic and is worth stating before the interface.
//
// videospec's central question is "what WILL this vendor render" — a video
// vendor's duration is chosen from the request, its resolution tier is derived,
// and for a token-billed vendor the billable quantity is a formula over both. So
// videospec.TokenEstimator's doc is explicit that it returns an ESTIMATE the
// balance gate tolerates drift on, and ctrl.WarnVideoTokenEstimateDrift exists to
// watch it going wrong.
//
// An audio vendor publishes a hard per-request output ceiling (Seed Audio: 120
// seconds). So the question here is "what is the MOST this can cost", and the
// answer is a genuine upper bound: the bill cannot exceed the hold. That makes
// the contract smaller — one method, one number, no outcome enum — and it means
// nothing here needs a drift warning. It also means concurrent creates from one
// wallet see each other exactly rather than approximately, which is the property
// the minimum-locked-balance floor exists to paper over when it does not hold.
//
// # Why the request does not enter into it
//
// An earlier version took the request's `max_duration` and reserved less when a
// caller asked for less. That was an UNDER-reservation, not a refinement: Seed
// Audio has no length parameter at all — the adaptor never forwarded the field,
// because the vendor has nothing to forward it to — so a request asking for 10
// seconds could still produce, and be billed for, 120. A bound a caller can lower
// without lowering the bill is not a bound.
//
// So the reserve is the ceiling itself, for every request. If a vendor that
// genuinely honours a per-request length ever arrives, give its Spec a method for
// that; do not reintroduce a request-shaped parameter here for a vendor that
// ignores it.
//
// Do not "improve" the reserve into a prediction of the actual length either (say,
// from the script's character count). A prediction that comes in low is
// indistinguishable from a correct bound until the bill arrives, and it arrives
// after the audio exists.
//
// # What is shared and what is not
//
// As in videospec, this file holds only the contract and the genuinely
// vendor-independent parts. Each vendor implements Spec in its own file and keeps
// its own rules; adding a vendor means adding ITS file and touching nothing else.
// There is deliberately no struct describing "the shape of a vendor's rules" —
// one sample is not a general form, and videospec's own doc records what happened
// when two samples looked alike and a third did not.
package audiospec

import "strings"

// Vendor identifies an audio-generation vendor. A deployment names one; it is a
// statement about which upstream is behind the translator, not a tunable.
type Vendor string

// Spec is what a vendor must be able to answer. Implementations live one per
// vendor file and share no structure — see the package doc.
type Spec interface {
	// MaxOutputSeconds is this vendor's hard per-request output ceiling, in
	// seconds. It is a fact about the vendor, not an operator's choice: a
	// deployment cannot raise it, and a request asking for more does not get
	// more.
	//
	// It is used twice, and the two uses must agree:
	//
	//   - as the RESERVE: what the balance gate holds before forwarding. Always the
	//     whole ceiling — see the package doc on why the request cannot lower it.
	//   - as the CLAMP on the bill: a reported duration above it is not believed,
	//     because the vendor cannot have produced it. Billing above the hold would
	//     also break the one property the reserve exists to guarantee.
	//
	// Must be positive. A zero or negative ceiling would reserve nothing and
	// silently disable the gate; TestEveryVendorHasAPositiveCeiling holds every
	// registered vendor to that.
	MaxOutputSeconds() int64
}

// specs is the registry, filled by each vendor's own file at init. Nothing
// enumerates vendors here.
//
// A vendor absent from it has no rules recorded, which callers must treat as
// "unknown", never as "assume the common case" — a guessed ceiling is a guessed
// hold.
var specs = map[Vendor]Spec{}

// normalize is the one spelling a vendor name is stored and looked up under.
// Applied on BOTH sides: Get already folded case and whitespace, but register did
// not, so a vendor file registering "SeedAudio" would have been unreachable by
// every lookup — including the exact string it registered — while every test that
// only looked names up through Get passed.
func normalize(v Vendor) Vendor {
	return Vendor(strings.ToLower(strings.TrimSpace(string(v))))
}

// register records one vendor's rules. Called from that vendor's own file at
// package init.
//
// It panics on a duplicate or an empty name rather than letting the last
// registration win: two files claiming one vendor is a merge accident, and which
// one wins would then depend on file order — with the losing set of rules
// silently sizing every reservation for that vendor. Both checks run on the
// NORMALIZED name, so "seedaudio" and " SeedAudio " collide as the same vendor
// they are, and a name of only whitespace is as empty as "".
func register(v Vendor, s Spec) {
	key := normalize(v)
	if key == "" {
		panic("audiospec: registered a spec with no vendor name")
	}
	if _, dup := specs[key]; dup {
		panic("audiospec: duplicate rules registered for vendor " + string(key))
	}
	specs[key] = s
}

// Get returns the rules recorded for a vendor. ok is false for a vendor nobody
// has recorded rules for — a caller that needs to hold funds must degrade
// explicitly there (forward unreserved and count it), not guess a ceiling.
func Get(v Vendor) (Spec, bool) {
	s, ok := specs[normalize(v)]
	return s, ok
}
