global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus-go"
    static_configs:
      - targets:
          [
            "router-0g-serving-provider-broker:3080",
            "router-0g-serving-provider-event:3081",
          ]
          # node-exporter
      - targets: ["router-prometheus-node-exporter:9100"]
