contractAddress: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
database:
  provider: root:123456@tcp(0g-serving-broker-db:3306)/provider?parseTime=true
event:
  providerAddr: ":8088"
interval:
  autoSettleBufferTime: 2
  forceSettlementProcessor: 60
  settlementProcessor: 1
servingUrl: http://192.168.2.142:8080
networks:
  ethereumHardhat:
    url: "http://hardhat-node-with-contract:8545"
    chainID: 31337
    privateKeys:
      - 59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
    transactionLimit: 9500000
    gasEstimationBuffer: 0
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
zkProver:
  provider: "zk-server:3000"
  requestLength: 40
