services:
  hardhat-node-with-contract:
    image: hardhat-node-with-contract:dev
    container_name: hardhat-node-with-contract
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      retries: 5

  mysql:
    image: mysql:8.0
    container_name: 0g-serving-broker-db
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - default

  0g-serving-provider-broker:
    image: ghcr.io/0glabs/0g-serving-broker:0.1.0
    container_name: 0g-serving-provider-broker
    environment:
      - PORT=3080
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - ./config-provider.yaml:/etc/config.yaml
    command: 0g-provider-server
    depends_on:
      mysql:
        condition: service_healthy
      hardhat-node-with-contract:
        condition: service_healthy
      zk:
        condition: service_healthy

  0g-serving-provider-event:
    image: ghcr.io/0glabs/0g-serving-broker:0.1.0
    container_name: 0g-serving-provider-event
    environment:
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - ./config-provider.yaml:/etc/config.yaml
    command: 0g-provider-event
    depends_on:
      0g-serving-provider-broker:
        condition: service_started

  nginx:
    image: nginx:1.27.0
    container_name: nginx-server
    ports:
      - "3080:80"
      - "30443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      0g-serving-provider-broker:
        condition: service_started

  zk:
    image: ghcr.io/0glabs/zk:0.1.0
    container_name: zk-server
    ports:
      - "3000:3000"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-X", "GET", "http://zk-server:3000/sign-keypair"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 30s

volumes:
  mysql-data:
