// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.20.3
// source: proto/tapp_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_DEBUG   LogLevel = 0
	LogLevel_INFO    LogLevel = 1
	LogLevel_WARNING LogLevel = 2
	LogLevel_ERROR   LogLevel = 3
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "DEBUG",
		1: "INFO",
		2: "WARNING",
		3: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"DEBUG":   0,
		"INFO":    1,
		"WARNING": 2,
		"ERROR":   3,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tapp_service_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_tapp_service_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{0}
}

type ServiceHealthStatus int32

const (
	ServiceHealthStatus_HEALTHY   ServiceHealthStatus = 0
	ServiceHealthStatus_UNHEALTHY ServiceHealthStatus = 1
	ServiceHealthStatus_UNKNOWN   ServiceHealthStatus = 2
)

// Enum value maps for ServiceHealthStatus.
var (
	ServiceHealthStatus_name = map[int32]string{
		0: "HEALTHY",
		1: "UNHEALTHY",
		2: "UNKNOWN",
	}
	ServiceHealthStatus_value = map[string]int32{
		"HEALTHY":   0,
		"UNHEALTHY": 1,
		"UNKNOWN":   2,
	}
)

func (x ServiceHealthStatus) Enum() *ServiceHealthStatus {
	p := new(ServiceHealthStatus)
	*p = x
	return p
}

func (x ServiceHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tapp_service_proto_enumTypes[1].Descriptor()
}

func (ServiceHealthStatus) Type() protoreflect.EnumType {
	return &file_proto_tapp_service_proto_enumTypes[1]
}

func (x ServiceHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceHealthStatus.Descriptor instead.
func (ServiceHealthStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{1}
}

type EvidenceFormat int32

const (
	EvidenceFormat_RAW_QUOTE          EvidenceFormat = 0 // Raw TDX quote
	EvidenceFormat_JSON_EVIDENCE      EvidenceFormat = 1 // JSON formatted evidence with metadata
	EvidenceFormat_COMPOSITE_EVIDENCE EvidenceFormat = 2 // Evidence with additional device attestations
)

// Enum value maps for EvidenceFormat.
var (
	EvidenceFormat_name = map[int32]string{
		0: "RAW_QUOTE",
		1: "JSON_EVIDENCE",
		2: "COMPOSITE_EVIDENCE",
	}
	EvidenceFormat_value = map[string]int32{
		"RAW_QUOTE":          0,
		"JSON_EVIDENCE":      1,
		"COMPOSITE_EVIDENCE": 2,
	}
)

func (x EvidenceFormat) Enum() *EvidenceFormat {
	p := new(EvidenceFormat)
	*p = x
	return p
}

func (x EvidenceFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvidenceFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tapp_service_proto_enumTypes[2].Descriptor()
}

func (EvidenceFormat) Type() protoreflect.EnumType {
	return &file_proto_tapp_service_proto_enumTypes[2]
}

func (x EvidenceFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvidenceFormat.Descriptor instead.
func (EvidenceFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{2}
}

// Start App Messages
type MountFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourcePath    string                 `protobuf:"bytes,1,opt,name=source_path,json=sourcePath,proto3" json:"source_path,omitempty"` // Source path in compose file, e.g., ./nginx.conf
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // File content (base64 encoded)
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`                               // File permissions, e.g., "0644"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MountFile) Reset() {
	*x = MountFile{}
	mi := &file_proto_tapp_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MountFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MountFile) ProtoMessage() {}

func (x *MountFile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MountFile.ProtoReflect.Descriptor instead.
func (*MountFile) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{0}
}

func (x *MountFile) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *MountFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *MountFile) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type StartAppRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ComposeContent string                 `protobuf:"bytes,1,opt,name=compose_content,json=composeContent,proto3" json:"compose_content,omitempty"`
	AppId          string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                // Application identifier for key binding
	MountFiles     []*MountFile           `protobuf:"bytes,3,rep,name=mount_files,json=mountFiles,proto3" json:"mount_files,omitempty"` // Files to mount (mapped by source_path from compose volumes)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartAppRequest) Reset() {
	*x = StartAppRequest{}
	mi := &file_proto_tapp_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAppRequest) ProtoMessage() {}

func (x *StartAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAppRequest.ProtoReflect.Descriptor instead.
func (*StartAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartAppRequest) GetComposeContent() string {
	if x != nil {
		return x.ComposeContent
	}
	return ""
}

func (x *StartAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StartAppRequest) GetMountFiles() []*MountFile {
	if x != nil {
		return x.MountFiles
	}
	return nil
}

type StartAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AppId         string                 `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // Application identifier
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`     // Timestamp of the start request
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartAppResponse) Reset() {
	*x = StartAppResponse{}
	mi := &file_proto_tapp_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartAppResponse) ProtoMessage() {}

func (x *StartAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartAppResponse.ProtoReflect.Descriptor instead.
func (*StartAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{2}
}

func (x *StartAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartAppResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StartAppResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StartAppResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Get Evidence Messages
type GetEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Signer        []byte                 `protobuf:"bytes,2,opt,name=signer,proto3" json:"signer,omitempty"` // Public key (32 bytes) to be included in report data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvidenceRequest) Reset() {
	*x = GetEvidenceRequest{}
	mi := &file_proto_tapp_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvidenceRequest) ProtoMessage() {}

func (x *GetEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvidenceRequest.ProtoReflect.Descriptor instead.
func (*GetEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetEvidenceRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetEvidenceRequest) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

type GetEvidenceResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Success  bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Evidence []byte                 `protobuf:"bytes,3,opt,name=evidence,proto3" json:"evidence,omitempty"`
	// Metadata
	TeeType       string `protobuf:"bytes,4,opt,name=tee_type,json=teeType,proto3" json:"tee_type,omitempty"` // TEE type (e.g., "TDX", "SNP", "SGX")
	Timestamp     int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`           // Evidence generation timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvidenceResponse) Reset() {
	*x = GetEvidenceResponse{}
	mi := &file_proto_tapp_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvidenceResponse) ProtoMessage() {}

func (x *GetEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvidenceResponse.ProtoReflect.Descriptor instead.
func (*GetEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetEvidenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetEvidenceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetEvidenceResponse) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *GetEvidenceResponse) GetTeeType() string {
	if x != nil {
		return x.TeeType
	}
	return ""
}

func (x *GetEvidenceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Get App Key Messages (replaces GetPubkey)
type GetAppKeyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`                              // Application identifier
	KeyType        string                 `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`                        // Key type: "ethereum", "rsa", "ec"
	AdditionalData []byte                 `protobuf:"bytes,3,opt,name=additional_data,json=additionalData,proto3" json:"additional_data,omitempty"`   // Additional binding data
	KbsResourceUri string                 `protobuf:"bytes,4,opt,name=kbs_resource_uri,json=kbsResourceUri,proto3" json:"kbs_resource_uri,omitempty"` // KBS resource URI for key material
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAppKeyRequest) Reset() {
	*x = GetAppKeyRequest{}
	mi := &file_proto_tapp_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppKeyRequest) ProtoMessage() {}

func (x *GetAppKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAppKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAppKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetAppKeyRequest) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *GetAppKeyRequest) GetAdditionalData() []byte {
	if x != nil {
		return x.AdditionalData
	}
	return nil
}

func (x *GetAppKeyRequest) GetKbsResourceUri() string {
	if x != nil {
		return x.KbsResourceUri
	}
	return ""
}

type GetAppKeyResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Key material (format depends on key_type)
	PublicKey []byte `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Public key bytes
	// Ethereum-specific fields (when key_type="ethereum")
	EthAddress []byte `protobuf:"bytes,4,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"` // 20-byte Ethereum address
	// Key provenance
	KeySource     string `protobuf:"bytes,5,opt,name=key_source,json=keySource,proto3" json:"key_source,omitempty"` // Source: "kbs", "in-memory"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppKeyResponse) Reset() {
	*x = GetAppKeyResponse{}
	mi := &file_proto_tapp_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppKeyResponse) ProtoMessage() {}

func (x *GetAppKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAppKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetAppKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAppKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAppKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetAppKeyResponse) GetEthAddress() []byte {
	if x != nil {
		return x.EthAddress
	}
	return nil
}

func (x *GetAppKeyResponse) GetKeySource() string {
	if x != nil {
		return x.KeySource
	}
	return ""
}

// Get App Secret Key Messages (local access only)
type GetAppSecretKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"` // Application identifier
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSecretKeyRequest) Reset() {
	*x = GetAppSecretKeyRequest{}
	mi := &file_proto_tapp_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSecretKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSecretKeyRequest) ProtoMessage() {}

func (x *GetAppSecretKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSecretKeyRequest.ProtoReflect.Descriptor instead.
func (*GetAppSecretKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetAppSecretKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetAppSecretKeyResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Secret key material (SENSITIVE - only for local access)
	PrivateKey    []byte `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"` // Private key bytes (32 bytes for Ethereum)
	PublicKey     []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`    // Public key bytes (for verification)
	EthAddress    []byte `protobuf:"bytes,5,opt,name=eth_address,json=ethAddress,proto3" json:"eth_address,omitempty"` // Ethereum address (if applicable)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppSecretKeyResponse) Reset() {
	*x = GetAppSecretKeyResponse{}
	mi := &file_proto_tapp_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppSecretKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppSecretKeyResponse) ProtoMessage() {}

func (x *GetAppSecretKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppSecretKeyResponse.ProtoReflect.Descriptor instead.
func (*GetAppSecretKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetAppSecretKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAppSecretKeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetAppSecretKeyResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *GetAppSecretKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetAppSecretKeyResponse) GetEthAddress() []byte {
	if x != nil {
		return x.EthAddress
	}
	return nil
}

// Service Status Messages
type GetServiceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"` // Optional: specific service name to check
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusRequest) Reset() {
	*x = GetServiceStatusRequest{}
	mi := &file_proto_tapp_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusRequest) ProtoMessage() {}

func (x *GetServiceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetServiceStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetServiceStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status          ServiceHealthStatus    `protobuf:"varint,2,opt,name=status,proto3,enum=tapp_service.ServiceHealthStatus" json:"status,omitempty"`
	StatusMessage   string                 `protobuf:"bytes,3,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	UptimeSeconds   int64                  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	MemoryUsageMb   int64                  `protobuf:"varint,5,opt,name=memory_usage_mb,json=memoryUsageMb,proto3" json:"memory_usage_mb,omitempty"`
	CpuUsagePercent float64                `protobuf:"fixed64,6,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	Pid             int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	Version         string                 `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// Attestation-related status
	AttestationAvailable bool   `protobuf:"varint,9,opt,name=attestation_available,json=attestationAvailable,proto3" json:"attestation_available,omitempty"`
	TeeType              string `protobuf:"bytes,10,opt,name=tee_type,json=teeType,proto3" json:"tee_type,omitempty"`
	KbsConnected         bool   `protobuf:"varint,11,opt,name=kbs_connected,json=kbsConnected,proto3" json:"kbs_connected,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_proto_tapp_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetStatus() ServiceHealthStatus {
	if x != nil {
		return x.Status
	}
	return ServiceHealthStatus_HEALTHY
}

func (x *ServiceInfo) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *ServiceInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServiceInfo) GetMemoryUsageMb() int64 {
	if x != nil {
		return x.MemoryUsageMb
	}
	return 0
}

func (x *ServiceInfo) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *ServiceInfo) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ServiceInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServiceInfo) GetAttestationAvailable() bool {
	if x != nil {
		return x.AttestationAvailable
	}
	return false
}

func (x *ServiceInfo) GetTeeType() string {
	if x != nil {
		return x.TeeType
	}
	return ""
}

func (x *ServiceInfo) GetKbsConnected() bool {
	if x != nil {
		return x.KbsConnected
	}
	return false
}

type GetServiceStatusResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Success   bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message   string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Services  []*ServiceInfo         `protobuf:"bytes,3,rep,name=services,proto3" json:"services,omitempty"`
	Timestamp int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Overall system status
	SystemHealthy bool   `protobuf:"varint,5,opt,name=system_healthy,json=systemHealthy,proto3" json:"system_healthy,omitempty"`
	SystemVersion string `protobuf:"bytes,6,opt,name=system_version,json=systemVersion,proto3" json:"system_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceStatusResponse) Reset() {
	*x = GetServiceStatusResponse{}
	mi := &file_proto_tapp_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceStatusResponse) ProtoMessage() {}

func (x *GetServiceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceStatusResponse.ProtoReflect.Descriptor instead.
func (*GetServiceStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetServiceStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetServiceStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServiceStatusResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

func (x *GetServiceStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetServiceStatusResponse) GetSystemHealthy() bool {
	if x != nil {
		return x.SystemHealthy
	}
	return false
}

func (x *GetServiceStatusResponse) GetSystemVersion() string {
	if x != nil {
		return x.SystemVersion
	}
	return ""
}

// Service Logs Messages
type GetServiceLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                    // Service name to get logs from (default: tapp-server)
	Lines         int32                  `protobuf:"varint,2,opt,name=lines,proto3" json:"lines,omitempty"`                                                  // Number of lines to retrieve (default: 100)
	Since         string                 `protobuf:"bytes,3,opt,name=since,proto3" json:"since,omitempty"`                                                   // Time filter: "1h", "30m", "2024-01-01 10:00:00"
	Until         string                 `protobuf:"bytes,4,opt,name=until,proto3" json:"until,omitempty"`                                                   // Time filter: "1h", "30m", "2024-01-01 10:00:00"
	MinLevel      LogLevel               `protobuf:"varint,5,opt,name=min_level,json=minLevel,proto3,enum=tapp_service.LogLevel" json:"min_level,omitempty"` // Minimum log level to include
	GrepPattern   string                 `protobuf:"bytes,6,opt,name=grep_pattern,json=grepPattern,proto3" json:"grep_pattern,omitempty"`                    // Pattern to filter log messages
	JsonFormat    bool                   `protobuf:"varint,7,opt,name=json_format,json=jsonFormat,proto3" json:"json_format,omitempty"`                      // Return logs in JSON format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogsRequest) Reset() {
	*x = GetServiceLogsRequest{}
	mi := &file_proto_tapp_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogsRequest) ProtoMessage() {}

func (x *GetServiceLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{12}
}

func (x *GetServiceLogsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetServiceLogsRequest) GetLines() int32 {
	if x != nil {
		return x.Lines
	}
	return 0
}

func (x *GetServiceLogsRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *GetServiceLogsRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *GetServiceLogsRequest) GetMinLevel() LogLevel {
	if x != nil {
		return x.MinLevel
	}
	return LogLevel_DEBUG
}

func (x *GetServiceLogsRequest) GetGrepPattern() string {
	if x != nil {
		return x.GrepPattern
	}
	return ""
}

func (x *GetServiceLogsRequest) GetJsonFormat() bool {
	if x != nil {
		return x.JsonFormat
	}
	return false
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                                         // Human-readable timestamp
	Level         LogLevel               `protobuf:"varint,2,opt,name=level,proto3,enum=tapp_service.LogLevel" json:"level,omitempty"`                                                     // Log level
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                             // Log message content
	ServiceName   string                 `protobuf:"bytes,4,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`                                                  // Service that generated the log
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_tapp_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{13}
}

func (x *LogEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *LogEntry) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_DEBUG
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *LogEntry) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetServiceLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Logs          []*LogEntry            `protobuf:"bytes,3,rep,name=logs,proto3" json:"logs,omitempty"`
	TotalLines    int32                  `protobuf:"varint,4,opt,name=total_lines,json=totalLines,proto3" json:"total_lines,omitempty"`
	Truncated     bool                   `protobuf:"varint,5,opt,name=truncated,proto3" json:"truncated,omitempty"` // Whether results were truncated
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceLogsResponse) Reset() {
	*x = GetServiceLogsResponse{}
	mi := &file_proto_tapp_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceLogsResponse) ProtoMessage() {}

func (x *GetServiceLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tapp_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceLogsResponse.ProtoReflect.Descriptor instead.
func (*GetServiceLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tapp_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetServiceLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetServiceLogsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetServiceLogsResponse) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *GetServiceLogsResponse) GetTotalLines() int32 {
	if x != nil {
		return x.TotalLines
	}
	return 0
}

func (x *GetServiceLogsResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_proto_tapp_service_proto protoreflect.FileDescriptor

const file_proto_tapp_service_proto_rawDesc = "" +
	"\n" +
	"\x18proto/tapp_service.proto\x12\ftapp_service\"Z\n" +
	"\tMountFile\x12\x1f\n" +
	"\vsource_path\x18\x01 \x01(\tR\n" +
	"sourcePath\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"\x8b\x01\n" +
	"\x0fStartAppRequest\x12'\n" +
	"\x0fcompose_content\x18\x01 \x01(\tR\x0ecomposeContent\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x128\n" +
	"\vmount_files\x18\x03 \x03(\v2\x17.tapp_service.MountFileR\n" +
	"mountFiles\"{\n" +
	"\x10StartAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x15\n" +
	"\x06app_id\x18\x04 \x01(\tR\x05appId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"C\n" +
	"\x12GetEvidenceRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x16\n" +
	"\x06signer\x18\x02 \x01(\fR\x06signer\"\x9e\x01\n" +
	"\x13GetEvidenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bevidence\x18\x03 \x01(\fR\bevidence\x12\x19\n" +
	"\btee_type\x18\x04 \x01(\tR\ateeType\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\x97\x01\n" +
	"\x10GetAppKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bkey_type\x18\x02 \x01(\tR\akeyType\x12'\n" +
	"\x0fadditional_data\x18\x03 \x01(\fR\x0eadditionalData\x12(\n" +
	"\x10kbs_resource_uri\x18\x04 \x01(\tR\x0ekbsResourceUri\"\xa6\x01\n" +
	"\x11GetAppKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\veth_address\x18\x04 \x01(\fR\n" +
	"ethAddress\x12\x1d\n" +
	"\n" +
	"key_source\x18\x05 \x01(\tR\tkeySource\"/\n" +
	"\x16GetAppSecretKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\xae\x01\n" +
	"\x17GetAppSecretKeyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x1f\n" +
	"\veth_address\x18\x05 \x01(\fR\n" +
	"ethAddress\"<\n" +
	"\x17GetServiceStatusRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x9f\x03\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x129\n" +
	"\x06status\x18\x02 \x01(\x0e2!.tapp_service.ServiceHealthStatusR\x06status\x12%\n" +
	"\x0estatus_message\x18\x03 \x01(\tR\rstatusMessage\x12%\n" +
	"\x0euptime_seconds\x18\x04 \x01(\x03R\ruptimeSeconds\x12&\n" +
	"\x0fmemory_usage_mb\x18\x05 \x01(\x03R\rmemoryUsageMb\x12*\n" +
	"\x11cpu_usage_percent\x18\x06 \x01(\x01R\x0fcpuUsagePercent\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x123\n" +
	"\x15attestation_available\x18\t \x01(\bR\x14attestationAvailable\x12\x19\n" +
	"\btee_type\x18\n" +
	" \x01(\tR\ateeType\x12#\n" +
	"\rkbs_connected\x18\v \x01(\bR\fkbsConnected\"\xf1\x01\n" +
	"\x18GetServiceStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x125\n" +
	"\bservices\x18\x03 \x03(\v2\x19.tapp_service.ServiceInfoR\bservices\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12%\n" +
	"\x0esystem_healthy\x18\x05 \x01(\bR\rsystemHealthy\x12%\n" +
	"\x0esystem_version\x18\x06 \x01(\tR\rsystemVersion\"\xf5\x01\n" +
	"\x15GetServiceLogsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05lines\x18\x02 \x01(\x05R\x05lines\x12\x14\n" +
	"\x05since\x18\x03 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\x04 \x01(\tR\x05until\x123\n" +
	"\tmin_level\x18\x05 \x01(\x0e2\x16.tapp_service.LogLevelR\bminLevel\x12!\n" +
	"\fgrep_pattern\x18\x06 \x01(\tR\vgrepPattern\x12\x1f\n" +
	"\vjson_format\x18\a \x01(\bR\n" +
	"jsonFormat\"\x92\x02\n" +
	"\bLogEntry\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12,\n" +
	"\x05level\x18\x02 \x01(\x0e2\x16.tapp_service.LogLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12!\n" +
	"\fservice_name\x18\x04 \x01(\tR\vserviceName\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.tapp_service.LogEntry.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb7\x01\n" +
	"\x16GetServiceLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04logs\x18\x03 \x03(\v2\x16.tapp_service.LogEntryR\x04logs\x12\x1f\n" +
	"\vtotal_lines\x18\x04 \x01(\x05R\n" +
	"totalLines\x12\x1c\n" +
	"\ttruncated\x18\x05 \x01(\bR\ttruncated*7\n" +
	"\bLogLevel\x12\t\n" +
	"\x05DEBUG\x10\x00\x12\b\n" +
	"\x04INFO\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*>\n" +
	"\x13ServiceHealthStatus\x12\v\n" +
	"\aHEALTHY\x10\x00\x12\r\n" +
	"\tUNHEALTHY\x10\x01\x12\v\n" +
	"\aUNKNOWN\x10\x02*J\n" +
	"\x0eEvidenceFormat\x12\r\n" +
	"\tRAW_QUOTE\x10\x00\x12\x11\n" +
	"\rJSON_EVIDENCE\x10\x01\x12\x16\n" +
	"\x12COMPOSITE_EVIDENCE\x10\x022\x9a\x04\n" +
	"\vTappService\x12I\n" +
	"\bStartApp\x12\x1d.tapp_service.StartAppRequest\x1a\x1e.tapp_service.StartAppResponse\x12R\n" +
	"\vGetEvidence\x12 .tapp_service.GetEvidenceRequest\x1a!.tapp_service.GetEvidenceResponse\x12L\n" +
	"\tGetAppKey\x12\x1e.tapp_service.GetAppKeyRequest\x1a\x1f.tapp_service.GetAppKeyResponse\x12^\n" +
	"\x0fGetAppSecretKey\x12$.tapp_service.GetAppSecretKeyRequest\x1a%.tapp_service.GetAppSecretKeyResponse\x12a\n" +
	"\x10GetServiceStatus\x12%.tapp_service.GetServiceStatusRequest\x1a&.tapp_service.GetServiceStatusResponse\x12[\n" +
	"\x0eGetServiceLogs\x12#.tapp_service.GetServiceLogsRequest\x1a$.tapp_service.GetServiceLogsResponseB?Z=github.com/0glabs/0g-serving-broker/common/tee/alicloud/protob\x06proto3"

var (
	file_proto_tapp_service_proto_rawDescOnce sync.Once
	file_proto_tapp_service_proto_rawDescData []byte
)

func file_proto_tapp_service_proto_rawDescGZIP() []byte {
	file_proto_tapp_service_proto_rawDescOnce.Do(func() {
		file_proto_tapp_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tapp_service_proto_rawDesc), len(file_proto_tapp_service_proto_rawDesc)))
	})
	return file_proto_tapp_service_proto_rawDescData
}

var file_proto_tapp_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_tapp_service_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_tapp_service_proto_goTypes = []any{
	(LogLevel)(0),                    // 0: tapp_service.LogLevel
	(ServiceHealthStatus)(0),         // 1: tapp_service.ServiceHealthStatus
	(EvidenceFormat)(0),              // 2: tapp_service.EvidenceFormat
	(*MountFile)(nil),                // 3: tapp_service.MountFile
	(*StartAppRequest)(nil),          // 4: tapp_service.StartAppRequest
	(*StartAppResponse)(nil),         // 5: tapp_service.StartAppResponse
	(*GetEvidenceRequest)(nil),       // 6: tapp_service.GetEvidenceRequest
	(*GetEvidenceResponse)(nil),      // 7: tapp_service.GetEvidenceResponse
	(*GetAppKeyRequest)(nil),         // 8: tapp_service.GetAppKeyRequest
	(*GetAppKeyResponse)(nil),        // 9: tapp_service.GetAppKeyResponse
	(*GetAppSecretKeyRequest)(nil),   // 10: tapp_service.GetAppSecretKeyRequest
	(*GetAppSecretKeyResponse)(nil),  // 11: tapp_service.GetAppSecretKeyResponse
	(*GetServiceStatusRequest)(nil),  // 12: tapp_service.GetServiceStatusRequest
	(*ServiceInfo)(nil),              // 13: tapp_service.ServiceInfo
	(*GetServiceStatusResponse)(nil), // 14: tapp_service.GetServiceStatusResponse
	(*GetServiceLogsRequest)(nil),    // 15: tapp_service.GetServiceLogsRequest
	(*LogEntry)(nil),                 // 16: tapp_service.LogEntry
	(*GetServiceLogsResponse)(nil),   // 17: tapp_service.GetServiceLogsResponse
	nil,                              // 18: tapp_service.LogEntry.MetadataEntry
}
var file_proto_tapp_service_proto_depIdxs = []int32{
	3,  // 0: tapp_service.StartAppRequest.mount_files:type_name -> tapp_service.MountFile
	1,  // 1: tapp_service.ServiceInfo.status:type_name -> tapp_service.ServiceHealthStatus
	13, // 2: tapp_service.GetServiceStatusResponse.services:type_name -> tapp_service.ServiceInfo
	0,  // 3: tapp_service.GetServiceLogsRequest.min_level:type_name -> tapp_service.LogLevel
	0,  // 4: tapp_service.LogEntry.level:type_name -> tapp_service.LogLevel
	18, // 5: tapp_service.LogEntry.metadata:type_name -> tapp_service.LogEntry.MetadataEntry
	16, // 6: tapp_service.GetServiceLogsResponse.logs:type_name -> tapp_service.LogEntry
	4,  // 7: tapp_service.TappService.StartApp:input_type -> tapp_service.StartAppRequest
	6,  // 8: tapp_service.TappService.GetEvidence:input_type -> tapp_service.GetEvidenceRequest
	8,  // 9: tapp_service.TappService.GetAppKey:input_type -> tapp_service.GetAppKeyRequest
	10, // 10: tapp_service.TappService.GetAppSecretKey:input_type -> tapp_service.GetAppSecretKeyRequest
	12, // 11: tapp_service.TappService.GetServiceStatus:input_type -> tapp_service.GetServiceStatusRequest
	15, // 12: tapp_service.TappService.GetServiceLogs:input_type -> tapp_service.GetServiceLogsRequest
	5,  // 13: tapp_service.TappService.StartApp:output_type -> tapp_service.StartAppResponse
	7,  // 14: tapp_service.TappService.GetEvidence:output_type -> tapp_service.GetEvidenceResponse
	9,  // 15: tapp_service.TappService.GetAppKey:output_type -> tapp_service.GetAppKeyResponse
	11, // 16: tapp_service.TappService.GetAppSecretKey:output_type -> tapp_service.GetAppSecretKeyResponse
	14, // 17: tapp_service.TappService.GetServiceStatus:output_type -> tapp_service.GetServiceStatusResponse
	17, // 18: tapp_service.TappService.GetServiceLogs:output_type -> tapp_service.GetServiceLogsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_tapp_service_proto_init() }
func file_proto_tapp_service_proto_init() {
	if File_proto_tapp_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tapp_service_proto_rawDesc), len(file_proto_tapp_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tapp_service_proto_goTypes,
		DependencyIndexes: file_proto_tapp_service_proto_depIdxs,
		EnumInfos:         file_proto_tapp_service_proto_enumTypes,
		MessageInfos:      file_proto_tapp_service_proto_msgTypes,
	}.Build()
	File_proto_tapp_service_proto = out.File
	file_proto_tapp_service_proto_goTypes = nil
	file_proto_tapp_service_proto_depIdxs = nil
}
