// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.20.3
// source: api/common/tee/alicloud/proto/tapp_service.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TappService_StartApp_FullMethodName            = "/tapp_service.TappService/StartApp"
	TappService_GetTaskStatus_FullMethodName       = "/tapp_service.TappService/GetTaskStatus"
	TappService_ListAppMeasurements_FullMethodName = "/tapp_service.TappService/ListAppMeasurements"
	TappService_GetEvidence_FullMethodName         = "/tapp_service.TappService/GetEvidence"
	TappService_GetAppKey_FullMethodName           = "/tapp_service.TappService/GetAppKey"
	TappService_GetAppSecretKey_FullMethodName     = "/tapp_service.TappService/GetAppSecretKey"
	TappService_GetServiceStatus_FullMethodName    = "/tapp_service.TappService/GetServiceStatus"
	TappService_GetServiceLogs_FullMethodName      = "/tapp_service.TappService/GetServiceLogs"
)

// TappServiceClient is the client API for TappService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type TappServiceClient interface {
	// Start an application using Docker Compose content (async - returns task ID)
	StartApp(ctx context.Context, in *StartAppRequest, opts ...grpc.CallOption) (*StartAppResponse, error)
	// Get task status for async operations
	GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error)
	// List all deployed applications' measurement information
	ListAppMeasurements(ctx context.Context, in *ListAppMeasurementsRequest, opts ...grpc.CallOption) (*ListAppMeasurementsResponse, error)
	// Get attestation evidence for external verifiers
	GetEvidence(ctx context.Context, in *GetEvidenceRequest, opts ...grpc.CallOption) (*GetEvidenceResponse, error)
	// Get application-bound key from KBS based on app ID
	GetAppKey(ctx context.Context, in *GetAppKeyRequest, opts ...grpc.CallOption) (*GetAppKeyResponse, error)
	// Get application secret key (private key) - local access only
	GetAppSecretKey(ctx context.Context, in *GetAppSecretKeyRequest, opts ...grpc.CallOption) (*GetAppSecretKeyResponse, error)
	// Get service status and health information
	GetServiceStatus(ctx context.Context, in *GetServiceStatusRequest, opts ...grpc.CallOption) (*GetServiceStatusResponse, error)
	// Get service logs with filtering options
	GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (*GetServiceLogsResponse, error)
}

type tappServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTappServiceClient(cc grpc.ClientConnInterface) TappServiceClient {
	return &tappServiceClient{cc}
}

func (c *tappServiceClient) StartApp(ctx context.Context, in *StartAppRequest, opts ...grpc.CallOption) (*StartAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartAppResponse)
	err := c.cc.Invoke(ctx, TappService_StartApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) GetTaskStatus(ctx context.Context, in *GetTaskStatusRequest, opts ...grpc.CallOption) (*GetTaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskStatusResponse)
	err := c.cc.Invoke(ctx, TappService_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) ListAppMeasurements(ctx context.Context, in *ListAppMeasurementsRequest, opts ...grpc.CallOption) (*ListAppMeasurementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAppMeasurementsResponse)
	err := c.cc.Invoke(ctx, TappService_ListAppMeasurements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) GetEvidence(ctx context.Context, in *GetEvidenceRequest, opts ...grpc.CallOption) (*GetEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvidenceResponse)
	err := c.cc.Invoke(ctx, TappService_GetEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) GetAppKey(ctx context.Context, in *GetAppKeyRequest, opts ...grpc.CallOption) (*GetAppKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppKeyResponse)
	err := c.cc.Invoke(ctx, TappService_GetAppKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) GetAppSecretKey(ctx context.Context, in *GetAppSecretKeyRequest, opts ...grpc.CallOption) (*GetAppSecretKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAppSecretKeyResponse)
	err := c.cc.Invoke(ctx, TappService_GetAppSecretKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) GetServiceStatus(ctx context.Context, in *GetServiceStatusRequest, opts ...grpc.CallOption) (*GetServiceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceStatusResponse)
	err := c.cc.Invoke(ctx, TappService_GetServiceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tappServiceClient) GetServiceLogs(ctx context.Context, in *GetServiceLogsRequest, opts ...grpc.CallOption) (*GetServiceLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceLogsResponse)
	err := c.cc.Invoke(ctx, TappService_GetServiceLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TappServiceServer is the server API for TappService service.
// All implementations must embed UnimplementedTappServiceServer
// for forward compatibility.
//
// Service definition
type TappServiceServer interface {
	// Start an application using Docker Compose content (async - returns task ID)
	StartApp(context.Context, *StartAppRequest) (*StartAppResponse, error)
	// Get task status for async operations
	GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error)
	// List all deployed applications' measurement information
	ListAppMeasurements(context.Context, *ListAppMeasurementsRequest) (*ListAppMeasurementsResponse, error)
	// Get attestation evidence for external verifiers
	GetEvidence(context.Context, *GetEvidenceRequest) (*GetEvidenceResponse, error)
	// Get application-bound key from KBS based on app ID
	GetAppKey(context.Context, *GetAppKeyRequest) (*GetAppKeyResponse, error)
	// Get application secret key (private key) - local access only
	GetAppSecretKey(context.Context, *GetAppSecretKeyRequest) (*GetAppSecretKeyResponse, error)
	// Get service status and health information
	GetServiceStatus(context.Context, *GetServiceStatusRequest) (*GetServiceStatusResponse, error)
	// Get service logs with filtering options
	GetServiceLogs(context.Context, *GetServiceLogsRequest) (*GetServiceLogsResponse, error)
	mustEmbedUnimplementedTappServiceServer()
}

// UnimplementedTappServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTappServiceServer struct{}

func (UnimplementedTappServiceServer) StartApp(context.Context, *StartAppRequest) (*StartAppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartApp not implemented")
}
func (UnimplementedTappServiceServer) GetTaskStatus(context.Context, *GetTaskStatusRequest) (*GetTaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedTappServiceServer) ListAppMeasurements(context.Context, *ListAppMeasurementsRequest) (*ListAppMeasurementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAppMeasurements not implemented")
}
func (UnimplementedTappServiceServer) GetEvidence(context.Context, *GetEvidenceRequest) (*GetEvidenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvidence not implemented")
}
func (UnimplementedTappServiceServer) GetAppKey(context.Context, *GetAppKeyRequest) (*GetAppKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppKey not implemented")
}
func (UnimplementedTappServiceServer) GetAppSecretKey(context.Context, *GetAppSecretKeyRequest) (*GetAppSecretKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppSecretKey not implemented")
}
func (UnimplementedTappServiceServer) GetServiceStatus(context.Context, *GetServiceStatusRequest) (*GetServiceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceStatus not implemented")
}
func (UnimplementedTappServiceServer) GetServiceLogs(context.Context, *GetServiceLogsRequest) (*GetServiceLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceLogs not implemented")
}
func (UnimplementedTappServiceServer) mustEmbedUnimplementedTappServiceServer() {}
func (UnimplementedTappServiceServer) testEmbeddedByValue()                     {}

// UnsafeTappServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TappServiceServer will
// result in compilation errors.
type UnsafeTappServiceServer interface {
	mustEmbedUnimplementedTappServiceServer()
}

func RegisterTappServiceServer(s grpc.ServiceRegistrar, srv TappServiceServer) {
	// If the following call pancis, it indicates UnimplementedTappServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TappService_ServiceDesc, srv)
}

func _TappService_StartApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).StartApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_StartApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).StartApp(ctx, req.(*StartAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetTaskStatus(ctx, req.(*GetTaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_ListAppMeasurements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAppMeasurementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).ListAppMeasurements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_ListAppMeasurements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).ListAppMeasurements(ctx, req.(*ListAppMeasurementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_GetEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetEvidence(ctx, req.(*GetEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_GetAppKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetAppKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetAppKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetAppKey(ctx, req.(*GetAppKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_GetAppSecretKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppSecretKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetAppSecretKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetAppSecretKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetAppSecretKey(ctx, req.(*GetAppSecretKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_GetServiceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetServiceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetServiceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetServiceStatus(ctx, req.(*GetServiceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TappService_GetServiceLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TappServiceServer).GetServiceLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TappService_GetServiceLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TappServiceServer).GetServiceLogs(ctx, req.(*GetServiceLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TappService_ServiceDesc is the grpc.ServiceDesc for TappService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TappService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tapp_service.TappService",
	HandlerType: (*TappServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartApp",
			Handler:    _TappService_StartApp_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _TappService_GetTaskStatus_Handler,
		},
		{
			MethodName: "ListAppMeasurements",
			Handler:    _TappService_ListAppMeasurements_Handler,
		},
		{
			MethodName: "GetEvidence",
			Handler:    _TappService_GetEvidence_Handler,
		},
		{
			MethodName: "GetAppKey",
			Handler:    _TappService_GetAppKey_Handler,
		},
		{
			MethodName: "GetAppSecretKey",
			Handler:    _TappService_GetAppSecretKey_Handler,
		},
		{
			MethodName: "GetServiceStatus",
			Handler:    _TappService_GetServiceStatus_Handler,
		},
		{
			MethodName: "GetServiceLogs",
			Handler:    _TappService_GetServiceLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/common/tee/alicloud/proto/tapp_service.proto",
}
