servingCA: 0x0165878A594ca255338adfa4d48449f69242Eb8F
ledgerCA: 0x8A791620dd6260079BF849Dc5567aDC3F2FdC318
database:
  router: root:123456@tcp(0g-serving-broker-db:3306)/router?parseTime=true
event:
  routerAddr: ":8089"
interval:
  refundProcessor: 1
networks:
  ethereumHardhat:
    url: "http://hardhat-node-with-contract:8545"
    chainID: 31337
    privateKeys:
      - 5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
    transactionLimit: 9500000
    gasEstimationBuffer: 0
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
zkProver:
  router: "zk-prover:3001"
  requestLength: 40
presetService:
  providerAddress: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
