services:
  router-hardhat-node-with-contract:
    image: raven20241/hardhat-compute-network-contract:dev
    container_name: router-hardhat-node-with-contract
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      retries: 5
    networks:
      - router

  router-mysql:
    image: mysql:8.0
    container_name: router-0g-serving-broker-db
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - router-mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - router

  router-0g-serving-provider-broker:
    image: ghcr.io/0glabs/0g-serving-broker:dev-amd64
    container_name: router-0g-serving-provider-broker
    ports:
      - "3080:3080"
    environment:
      - PORT=3080
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - ./config-provider.local.yaml:/etc/config.yaml
    command: 0g-inference-server
    networks:
      - router
    depends_on:
      router-mysql:
        condition: service_healthy
      router-hardhat-node-with-contract:
        condition: service_healthy
      router-zk-prover:
        condition: service_healthy

  router-0g-serving-provider-event:
    image: ghcr.io/0glabs/0g-serving-broker:dev-amd64
    container_name: router-0g-serving-provider-event
    environment:
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - ./config-provider.local.yaml:/etc/config.yaml
    command: 0g-inference-event
    networks:
      - router
    depends_on:
      router-0g-serving-provider-broker:
        condition: service_started
      router-zk-settlement:
        condition: service_healthy

  router-zk-prover:
    image: ghcr.io/0glabs/zk:0.1.0
    container_name: router-zk-prover
    volumes:
      - ./logs:/app/logs
    environment:
      JS_PROVER_PORT: 3001
    ports:
      - "3001:3001"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-X",
          "GET",
          "http://router-zk-prover:3001/sign-keypair",
        ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 30s
    networks:
      - router

  router-zk-settlement:
    image: ghcr.io/0glabs/zk:0.1.0
    container_name: router-zk-settlement
    volumes:
      - ./logs:/app/logs
    environment:
      JS_PROVER_PORT: 3002
    ports:
      - "3002:3002"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-X",
          "GET",
          "http://router-zk-settlement:3002/sign-keypair",
        ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 30s
    networks:
      - router

  router-prometheus:
    image: prom/prometheus:v2.45.2
    container_name: router-prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - router

  router-grafana:
    image: grafana/grafana-oss:11.4.0
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    container_name: router-grafana
    ports:
      - "3003:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - router
    depends_on:
      - router-prometheus

  # source https://github.com/prometheus/node_exporter
  # https://github.com/vegasbrianc/prometheus/
  router-prometheus-node-exporter:
    image: prom/node-exporter:v1.7.0
    container_name: router-prometheus-node-exporter
    restart: always
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      - router
    privileged: true
    depends_on:
      - router-prometheus
    expose:
      - 9100

  router-0g-serving-router:
    image: ghcr.io/0glabs/0g-serving-broker:dev-amd64
    container_name: router-0g-serving-router
    ports:
      - "1034:1034"
    environment:
      - PORT=1034
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - ./config-router.yaml:/etc/config.yaml
    command: 0g-inference-router-server
    networks:
      - router
    depends_on:
      router-mysql:
        condition: service_healthy
      router-hardhat-node-with-contract:
        condition: service_healthy
      router-zk-prover:
        condition: service_healthy

volumes:
  router-mysql-data:

networks:
  router:
    name: router
    external: false
