num_train_epochs = 3
per_device_train_batch_size = 16
per_device_eval_batch_size = 16
warmup_steps = 500
weight_decay = 0.01
logging_dir = "./logs"
logging_steps = 100
evaluation_strategy = "no"
save_strategy = "steps"
save_steps = 500
eval_steps = 500
load_best_model_at_end = false
metric_for_best_model = "accuracy"
greater_is_better = true
report_to = ["none"]
