network: zgTestnetDev
privateKey: ""
nodeInfo:
  provider: "0xa736Ae91059CaD03Ec89c107c158f7Fc54bB3e18"
blockchain:
  rpcUrl: "https://evmrpc-testnet.0g.ai"
  chainId: 16600
  transactionLimit: 10000000
  gasEstimationBuffer: 100000
images:
  executionImageName: "ghcr.io/0gfoundation/fine-tuning-test:v1"
  executionMockImageName: "ghcr.io/0gfoundation/fine-tuning-test:v1"
  buildImage: false
service:
  servingUrl: "https://d4872603ae17c78f5d3a35318da14daedacf28a8-80.dstack-pha-use2.phala.network"
  pricePerToken: 1
  quota:
    cpuCount: 8
    memory: 187
    storage: 900
    gpuType: "H200"
    gpuCount: 1
  # Local model paths
  modelLocalPaths:
    "0xb4f76a886b8655c92bb021922d60b5e4d9271a5c9da98b6cb10937a06c2c75a7": "/dstack/persistent/models/Qwen2.5-0.5B-Instruct"
    "0x2e6f9620c35bdcb2b753cc7aa34e78077a8ed133e36fa36008fd6bdfd29af3a5": "/dstack/persistent/models/Qwen3-32B"
  # HuggingFace fallback
  modelHuggingFaceFallback:
    "0xb4f76a886b8655c92bb021922d60b5e4d9271a5c9da98b6cb10937a06c2c75a7": "Qwen/Qwen2.5-0.5B-Instruct"
    "0x2e6f9620c35bdcb2b753cc7aa34e78077a8ed133e36fa36008fd6bdfd29af3a5": "Qwen/Qwen3-32B"
database:
  mysql:
    host: "mysql"
    port: 3306
    user: "root"
    password: "my_root_password"
    db: "fine_tuning"
zgStorage:
  indexerUrl: "https://indexer-storage-testnet-turbo.0g.ai"
  evmRpc: "https://evmrpc-testnet.0g.ai"
  flowAddress: "0x0460aA47b41a66694c0a73f667a1b795A5ED3556"
  privateKey: ""
finalizerWorkerCount: 1
executorWorkerCount: 1
setupWorkerCount: 1
maxSetupRetriesPerTask: 3
maxExecutorRetriesPerTask: 3
maxFinalizerRetriesPerTask: 10
maxSettlementRetriesPerTask: 10
settlementBatchSize: 1
deliveredTaskAckTimeoutSecs: 21600
dataRetentionDays: 3
maxTaskQueueSize: 5
