contractAddress: 0x38ae6632E63B61153A6FbCD163E79af1855EDa8B
database:
  fineTune: root:123456@tcp(localhost:33060)/fineTune?parseTime=true
networks:
  ethereumHardhat:
    url: "http://127.0.0.1:8545/"
    chainID: 31337
    privateKeys:
      - 5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a
    transactionLimit: 9500000
    gasEstimationBuffer: 0
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16600
    privateKeys:
      - 1111111111111111111111111111111111111111111111111111111111
    transactionLimit: 10000000
    gasEstimationBuffer: 100000
service:
  servingUrl: "http://192.168.1.103:3080"
  pricePerToken: 1
  quota:
    cpuCount: 8
    memory: 16
    storage: 10
    gpuType: "H200"
    gpuCount: 1
storageClient:
  indexerStandard: "https://indexer-storage-testnet-standard.0g.ai"
  indexerTurbo: "https://indexer-storage-testnet-turbo.0g.ai"
  uploadArgs:
    finalityRequired: true
    tags: "0x"
    expectedReplica: 1
    skipTx: false
    taskSize: 4
    fragmentSize: 4294967296
    routines: 4
logger:
  level: "debug"
