services:
  config-init:
    image: alpine:latest
    volumes:
      - config-vol:/config
    command: sh -c 'echo "bmV0d29ya3M6CiAgZXRoZXJldW0wZzoKICAgIHVybDogImh0dHBzOi8vZXZtcnBjLXRlc3RuZXQuMGcuYWkiCiAgICBjaGFpbklEOiAxNjYwMgogICAgcHJpdmF0ZUtleXM6CiAgICAgIC0gIjJDRTQ2QTFDM0I1RTVGNzNFREI3OUMzNDNCQjg2OUVGOTQ3MDlFNkJFQkIzQjI5QjcwOTM3RDdCNUM2RDU3NTEiCiAgICB0cmFuc2FjdGlvbkxpbWl0OiAxMDAwMDAwCnNlcnZpY2U6CiAgc2VydmluZ1VybDogIiNEU1RBQ0tfQVBQX1VSTCMiCiAgcHJpY2VQZXJUb2tlbjogMQogIHF1b3RhOgogICAgY3B1Q291bnQ6IDgKICAgIG1lbW9yeTogMTg3CiAgICBzdG9yYWdlOiA5MDAKICAgIGdwdVR5cGU6IEgyMDAKICAgIGdwdUNvdW50OiAxCiAgbW9kZWxMb2NhbFBhdGhzOgogICAgIjB4MmU2Zjk2MjBjMzViZGNiMmI3NTNjYzdhYTM0ZTc4MDc3YThlZDEzM2UzNmZhMzYwMDhmZDZiZGZkMjlhZjNhNSI6IC9kc3RhY2svcGVyc2lzdGVudC9tb2RlbHMvUXdlbjMtMzJCCiAgbW9kZWxIdWdnaW5nRmFjZUZhbGxiYWNrOgogICAgIjB4MmU2Zjk2MjBjMzViZGNiMmI3NTNjYzdhYTM0ZTc4MDc3YThlZDEzM2UzNmZhMzYwMDhmZDZiZGZkMjlhZjNhNSI6IFF3ZW4vUXdlbjMtMzJCCiAgc2tpcFN0b3JhZ2VVcGxvYWQ6IHRydWUKICBmaWxlUmV0ZW50aW9uSG91cnM6IDcyCmRhdGFiYXNlOgogIGZpbmVUdW5lOiByb290OjEyMzQ1NkB0Y3AoMGctZmluZS10dW5lLWJyb2tlci1kYjozMzA2KS9maW5lVHVuZT9wYXJzZVRpbWU9dHJ1ZQpsb2dnZXI6CiAgbGV2ZWw6IGRlYnVnCiAgcGF0aDogL3RtcC9maW5lLXR1bmluZy5sb2cKZmluYWxpemVyV29ya2VyQ291bnQ6IDEKdHJhaW5pbmdXb3JrZXJDb3VudDogMQpzZXR1cFdvcmtlckNvdW50OiAxCm1heFNldHVwUmV0cmllc1BlclRhc2s6IDMKbWF4RXhlY3V0b3JSZXRyaWVzUGVyVGFzazogMwptYXhGaW5hbGl6ZXJSZXRyaWVzUGVyVGFzazogMTAKbWF4U2V0dGxlbWVudFJldHJpZXNQZXJUYXNrOiAxMApzZXR0bGVtZW50QmF0Y2hTaXplOiAxCmRlbGl2ZXJlZFRhc2tBY2tUaW1lb3V0U2VjczogMjE2MDAKZGF0YVJldGVudGlvbkRheXM6IDMKbWF4VGFza1F1ZXVlU2l6ZTogNQo=" | base64 -d > /config/config.yaml'

  mysql:
    image: mysql:8.0
    container_name: 0g-fine-tune-broker-db
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fineTune
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - localhost
    depends_on:
      config-init:
        condition: service_completed_successfully

  0g-fine-tune-broker:
    image: ghcr.io/0gfoundation/0g-serving-broker:2d03306-fix-amd64
    privileged: true
    restart: always
    container_name: 0g-fine-tune-broker
    environment:
      - PORT=3080
      - CONFIG_FILE=/etc/config/config.yaml
      - NVIDIA_VISIBLE_DEVICES=all
      - TOKEN=PHALA@2025
    ports:
      - "80:3080"
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - config-vol:/etc/config:ro
      - /tmp:/tmp
      - /tmp/0g-transformer-bridge:/opt/transformer-bridge
      - ./models:/fine-tuning/execution/models
      - /dstack/persistent:/dstack/persistent
    command: ["0g-fine-tuning-server", "--config", "/etc/config/config.yaml"]
    networks:
      - localhost
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql-data:
  config-vol:

networks:
  localhost:
    name: localhost
    external: false
