services:
  mysql:
    image: mysql:8.0
    container_name: 0g-serving-provider-broker-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: provider
      MYSQL_PASSWORD: provider
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - localhost

  0g-serving-provider-broker:
    image: ghcr.io/0glabs/0g-serving-broker:0.1.0
    container_name: 0g-serving-provider-broker
    environment:
      - PORT=3080
      - CONFIG_FILE=/etc/config.yaml
    volumes:
      - ./config.local.yaml:/etc/config.yaml
    command: 0g-provider-server
    networks:
      - localhost
    depends_on:
      mysql:
        condition: service_healthy
      zk:
        condition: service_healthy

  0g-serving-provider-event:
    image: ghcr.io/0glabs/0g-serving-broker:0.1.0
    container_name: 0g-serving-provider-event
    environment:
      - CONFIG_FILE=/etc/config.yaml
    volumes:
      - ./config.local.yaml:/etc/config.yaml
    command: 0g-provider-event
    networks:
      - localhost
    depends_on:
      0g-serving-provider-broker:
        condition: service_started

  nginx:
    image: nginx:1.27.0
    container_name: nginx-server
    ports:
      - "#PORT#:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - localhost
    depends_on:
      0g-serving-provider-broker:
        condition: service_started

  zk:
    image: ghcr.io/0glabs/zk:0.1.0
    container_name: zk-provider-server
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "-X",
          "GET",
          "http://zk-provider-server:3000/sign-keypair",
        ]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 30s
    networks:
      - localhost

volumes:
  mysql-data:

networks:
  localhost:
    name: localhost
    external: false
