services:
  hardhat-node-with-contract:
    image: raven20241/hardhat-compute-network-contract:dev
    container_name: hardhat-node-with-contract
    ports:
      - "8545:8545"
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      retries: 5
    networks:
      - localhost

  mysql:
    image: mysql:8.0
    container_name: 0g-fine-tune-broker-db
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=fineTune
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - localhost

  0g-fine-tune-broker:
    image: ghcr.io/0gfoundation/0g-serving-broker:dev-amd64
    privileged: true
    restart: always
    container_name: 0g-fine-tune-broker
    ports:
      - "3080:3080"
    environment:
      - PORT=3080
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.local.yaml:/etc/config.yaml
      - /tmp:/tmp
      - /tmp/0g-transformer-bridge:/opt/transformer-bridge
    command: 0g-fine-tuning-server
    networks:
      - localhost
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
    depends_on:
      mysql:
        condition: service_healthy
      hardhat-node-with-contract:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  localhost:
    name: localhost
    external: false
