services:
  mysql-router:
    image: mysql:8.0
    container_name: 0g-serving-router-db
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql-data-router:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
    networks:
      - router-network

  0g-serving-router:
    image: ghcr.io/0glabs/0g-serving-broker:dev-amd64
    container_name: 0g-serving-router
    ports:
      - "1034:1034"
    environment:
      - PORT=1034
      - CONFIG_FILE=/etc/config.yaml
      - NETWORK=hardhat
    volumes:
      - ./config-router.yaml:/etc/config.yaml
    command: 0g-inference-router-server
    networks:
      - router-network
    depends_on:
      mysql-router:
        condition: service_healthy
      zk-prover:
        condition: service_healthy

  nginx-router:
    image: nginx:1.27.0
    container_name: nginx-router-server
    ports:
      - "3082:80"
      - "30445:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certificate.pem:/etc/nginx/certificate.pem
      - ./privatekey.pem:/etc/nginx/privatekey.pem
    networks:
      - router-network
    depends_on:
      0g-serving-router:
        condition: service_started

  zk-prover:
    image: ghcr.io/0glabs/zk:0.2.1
    container_name: zk-prover
    environment:
      JS_PROVER_PORT: 3001
    ports:
      - "3001:3001"
    healthcheck:
      test:
        ["CMD", "curl", "-f", "-X", "GET", "http://zk-prover:3001/sign-keypair"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 30s
    networks:
      - localhost

volumes:
  mysql-data-router:

networks:
  router-network:
    name: router-network
    external: false
