interval:
  autoSettleBufferTime: 60
  forceSettlementProcessor: 600
  settlementProcessor: 300
networks:
  ethereum0g:
    url: "https://evmrpc-testnet.0g.ai"
    chainID: 16601
    privateKeys:
      - <Private_Key>
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
service:
  servingUrl: <Serving URL>
  targetUrl: <Target URL>
  inputPrice: <Input Price>
  outputPrice: <Output Price>
  type: "chatbot"
  model: <Model>
  verifiability: "TeeML"
