interval:
  autoSettleBufferTime: 60
  forceSettlementProcessor: 600
  settlementProcessor: 300
networks:
  ethereum0g:
    url: "http://8.218.94.246:8545"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
service:
  servingUrl: <Serving URL>
  targetUrl: <Target URL>
  inputPrice: 1
  outputPrice: 1
  type: "chatbot"
  model: <Model>
  verifiability: "TeeML"
