interval:
  autoSettleBufferTime: 60
  forceSettlementProcessor: 600
  settlementProcessor: 300
servingUrl: http://<Public_IP_Address>:<PORT>
networks:
  ethereum0g:
    url: "https://0g-json-rpc-public.originstake.com"
    chainID: 16600
    privateKeys:
      - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    transactionLimit: 1000000
    gasEstimationBuffer: 10000
