database:
  # MySQL DSN. The broker connects to 0g-serving-provider-broker-db:3306 by
  # default. Do not change if using docker compose to start service.
  dsn: provider:provider@tcp(0g-serving-provider-broker-db:3306)/provider?parseTime=true

contractAddress:

# 0G storage indexer URLs
indexerStandardUrl: "https://indexer-storage-testnet-standard.0g.ai"
indexerTurboUrl: "https://indexer-storage-testnet-turbo.0g.ai"

event:
  # Listen address for the event process's metrics HTTP server.
  listenAddr: ":8088"

interval:
  # Buffer time for automatic settlements (Go duration string).
  autoSettleBufferTime: "60s"

  # Interval for running the force settlement processor.
  # Must be > 1m to prevent overly frequent settlements.
  forceSettlementProcessor: "10m"

  # Interval for running the settlement processor.
  settlementProcessor: "5m"

network:
  url: "https://evmrpc-testnet.0g.ai"
  chainID: 16602
  privateKeys:
    - aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  transactionLimit: 5000000
  gasEstimationBuffer: 100000

zkProver:
  # Host of zk prover broker.
  # Do not change this configuration if using docker compose to start service.
  host: "zk-provider-server:3000"

  # requestLength defines the number of requests prover broker packs into one
  # chunk as the minimum unit for settlement.
  requestLength: 40
